apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-task
spec:
  selector:
    matchLabels:
      app: add-task
  template:
    metadata:
      labels:
        app: add-task
        
    spec:
      containers:
      - name: add-task
        image: rakeshacr.azurecr.io/addtask:v1
        ports:
        - containerPort: 8000
        env:
        - name: CONNECTION_STRING
          value: "Driver={ODBC Driver 18 for SQL Server};Server=tcp:rakeshdbs01.database.windows.net,1433;Database=rakeshsqldb01;Uid=azureuser;Pwd={your_password_here};Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
